import { createContext, useContext, useState, type ReactNode } from 'react'

export type Lang = 'vi' | 'en'

const translations: Record<Lang, Record<string, string>> = {
  vi: {
    'nav.dashboard': 'Dashboard',
    'nav.my_documents': 'My Documents',
    'nav.shared': 'Shared',
    'nav.connect': 'Kết nối ví',
    'nav.profile': 'Trang cá nhân',
    'nav.settings': 'Cài đặt',
    'nav.logout': 'Đăng xuất',
    'nav.light_mode': 'Light mode',
    'nav.dark_mode': 'Dark mode',
    'sidebar.dashboard': 'Dashboard',
    'sidebar.my_documents': 'My Documents',
    'sidebar.ai_analysis': 'AI Analysis',
    'sidebar.favorites': 'Yêu thích',
    'sidebar.recent': 'Gần đây',
    'sidebar.trash': 'Thùng rác',
    'sidebar.folders': 'Thư mục',
    'sidebar.new_folder': 'Thư mục mới',
    'sidebar.upload_file': 'Tải file lên',
    'sidebar.storage': 'Lưu trữ',
    'sidebar.profile': 'Trang cá nhân',
    'sidebar.settings': 'Cài đặt',
    'sidebar.etherscan': 'Xem trên Etherscan',
    'sidebar.logout': 'Đăng xuất',
    'profile.back': '← Quay lại',
    'profile.edit': 'Chỉnh sửa hồ sơ',
    'profile.overview': 'Tổng quan',
    'profile.web3': 'Web3 Identity',
    'profile.activity': 'Hoạt động',
    'profile.storage': 'Lưu trữ',
    'profile.security': 'Bảo mật',
    'profile.edit_tab': 'Chỉnh sửa',
    'profile.upload_avatar': 'Đổi ảnh đại diện',
    'profile.storage_used': 'MB đã dùng',
    'profile.storage_of': '/',
    'profile.usage_percent': '% đã dùng',
    'profile.upgrade_pro': 'Nâng cấp lên Pro',
    'profile.account_info': 'Thông tin tài khoản',
    'profile.user_id': 'User ID',
    'profile.joined': 'Tham gia',
    'profile.auth_method': 'Xác thực',
    'profile.public_profile': 'Hồ sơ công khai',
    'profile.yes': 'Có',
    'profile.no': 'Không',
    'profile.ens_name': 'ENS Name',
    'profile.no_ens': 'Chưa có ENS name. Đăng ký để hiển thị tên thay vì địa chỉ ví.',
    'profile.register_ens': 'Đăng ký ENS',
    'profile.nfts': 'DocVault NFTs',
    'profile.no_nfts': 'Chưa có DocNFT. Mint NFT bằng cách verify tài liệu on-chain.',
    'profile.onchain_stats': 'On-chain Stats',
    'profile.docs_onchain': 'Docs on-chain',
    'profile.signings': 'Signings',
    'profile.nfts_minted': 'NFTs minted',
    'profile.activity_history': 'Lịch sử hoạt động',
    'profile.loading_activity': 'Đang tải lịch sử hoạt động...',
    'profile.storage_detail': 'Chi tiết dung lượng',
    'profile.used': 'Đã dùng',
    'profile.remaining': 'Còn lại',
    'profile.total_limit': 'Tổng giới hạn',
    'profile.plan_free': 'Miễn phí',
    'profile.plan_pro': 'Pro',
    'profile.plan_business': 'Business',
    'profile.plan_enterprise': 'Enterprise',
    'profile.current': 'Hiện tại',
    'profile.upgrade': 'Nâng cấp',
    'profile.security_title': 'Bảo mật',
    'profile.wallet_auth': 'Xác thực ví Web3',
    'profile.wallet_auth_desc': 'Đăng nhập bằng MetaMask signature — không cần mật khẩu.',
    'profile.nonce_rotation': 'Nonce rotation',
    'profile.nonce_rotation_desc': 'Nonce mới sau mỗi lần đăng nhập — chống replay attack.',
    'profile.jwt_expiry': 'JWT tự động hết hạn',
    'profile.jwt_expiry_desc': 'Token hết hạn sau 7 ngày, cần ký lại để gia hạn.',
    'profile.e2e_encryption': 'Mã hóa end-to-end (IPFS)',
    'profile.e2e_encryption_desc': 'Nội dung file được mã hóa trước khi đẩy lên IPFS.',
    'profile.enabled': 'Đã bật',
    'profile.active': 'Đang hoạt động',
    'profile.days': 'ngày',
    'profile.coming_soon': 'Sắp ra mắt',
    'profile.edit_info': 'Thông tin cơ bản',
    'profile.saved': 'Đã lưu',
    'profile.display_name': 'Tên hiển thị',
    'profile.bio': 'Bio',
    'profile.twitter': 'Twitter/X',
    'profile.github': 'GitHub',
    'profile.website': 'Website',
    'profile.public_toggle': 'Hồ sơ công khai',
    'profile.save_changes': 'Lưu thay đổi',
    'profile.documents': 'Tài liệu',
    'profile.verified': 'Đã verify',
    'profile.on_chain': 'On-Chain',
    'profile.shared': 'Đã chia sẻ',
    'profile.signed': 'Đã ký',
    'profile.anonymous': 'Anonymous',
    'profile.saving': 'Đang lưu...',
    'profile.logout': 'Đăng xuất',
    'profile.price_free': 'Miễn phí',
    'profile.price_pro': '$19/tháng',
    'profile.price_business': '$79/tháng',
    'profile.price_enterprise': '$299/tháng',
    'profile.unlimited': 'Unlimited',
    'profile.nfts_count': 'NFTs',
    'profile.placeholder_display_name': 'Nhập tên hiển thị...',
    'profile.placeholder_bio': 'Giới thiệu ngắn về bạn...',
    'profile.placeholder_twitter': 'https://twitter.com/...',
    'profile.placeholder_github': 'https://github.com/...',
    'profile.placeholder_website': 'https://...',
    'home.hero_title': 'Quản lý tài liệu',
    'home.hero_subtitle': 'Bảo mật với Web3 + AI',
    'home.connect_prompt': '🚀 Bắt đầu ngay bằng ví Web3',
    'home.terms': 'Điều khoản',
    'home.privacy': 'Chính sách bảo mật',
    'home.contact': 'Liên hệ',
    'home.copyright': '© 2024 DocVault Ecosystem. Secure Optimism.',
    'dashboard.dashboard_title': 'Bảng điều khiển',
    'dashboard.dashboard_subtitle': 'Quản lý tài liệu, xác minh AI và lưu trữ blockchain',
    'dashboard.document_name': 'Document Name',
    'dashboard.type': 'Type',
    'dashboard.status': 'Status',
    'dashboard.date': 'Date',
    'dashboard.actions': 'Actions',
    'dashboard.no_documents': 'Chưa có tài liệu nào',
    'dashboard.folder_label': 'folder',
    'dashboard.onchain_badge': 'On-Chain',
    'dashboard.ai_verified_badge': 'AI Verified',
    'dashboard.pending_badge': 'Pending',
    'dashboard.save_proof_onchain': 'Lưu Proof On-Chain',
    'dashboard.saved_onchain': 'Đã lưu On-Chain',
    'dashboard.share': 'Share',
    'dashboard.ai_summary': 'AI Summary',
    'dashboard.select_doc_prompt_title': 'Chọn một tài liệu trong bảng',
    'dashboard.select_doc_prompt_subtitle': 'để xem chi tiết',
    'dashboard.password_required': 'Mật khẩu yêu cầu',
    'dashboard.password_protected_message': 'Tài liệu này được bảo vệ bằng mật khẩu. Vui lòng nhập mật khẩu để xem.',
    'dashboard.enter_password': 'Nhập mật khẩu...',
    'dashboard.password_required_error': 'Vui lòng nhập mật khẩu',
    'dashboard.wrong_password': 'Sai mật khẩu',
    'dashboard.cancel': 'Hủy',
    'dashboard.verifying': 'Đang kiểm tra...',
    'dashboard.confirm': 'Xác nhận',
    'dashboard.open_folder': 'Open folder',
    'dashboard.preview': 'Preview',
    'dashboard.star': 'Star',
    'dashboard.unstar': 'Unstar',
    'dashboard.store_on_chain': 'Store On-Chain',
    'dashboard.store_all_on_chain': 'Store all On-Chain',
    'dashboard.delete': 'Delete',
    'dashboard.delete_folder': 'Delete folder',
    'dashboard.docvault': 'DocVault',
    'dashboard.favorites': 'Favorites',
    'dashboard.recent': 'Recent',
    'dashboard.trash': 'Trash',
    'dashboard.deleted_documents': 'Deleted documents',
    'dashboard.favorite_documents': 'Favorite documents',
    'dashboard.recent_documents': 'Recent documents',
    'dashboard.all_documents': 'All documents',
    'dashboard.search': 'Search...',
    'dashboard.upload': 'Upload',
    'dashboard.search_results': 'Search results',
    'dashboard.files_found': 'files',
    'dashboard.no_results_found': 'No results found',
    'dashboard.clear': 'Clear',
    'dashboard.trash_is_empty': 'Trash is empty',
    'dashboard.no_favorite_documents': 'No favorite documents',
    'dashboard.no_documents_yet': 'No documents yet',
    'dashboard.upload_now': 'Tải lên ngay',
    'dashboard.unknown_type': 'unknown',
    'dashboard.my_files': 'My Files',
    'dashboard.name': 'Name',
    'dashboard.size': 'Size',
    'dashboard.shared_with_me': 'Shared with me',
    'dashboard.no_shared_documents': 'Chưa có tài liệu nào được chia sẻ với bạn',
    'dashboard.edit_permission': 'Edit',
    'dashboard.view_permission': 'View',
    'dashboard.from_user': 'from',
    'dashboard.back_to_root': 'Back to root',
    'dashboard.percent_used': '% used',
    'dashboard.switch_language': 'Chuyển sang Tiếng Việt',
    'dashboard.light_mode': 'Light mode',
    'dashboard.dark_mode': 'Dark mode',
    'dashboard.anonymous': 'Anonymous',
    'dashboard.ai_analysis_title': 'AI Analysis',
    'dashboard.ai_analysis_subtitle': 'Phân tích tài liệu với AI',
    'dashboard.ai_chat_clauses_tab': 'AI Chat & Clauses',
    'dashboard.compare_tab': 'So sánh AI',
    'dashboard.select_document_label': 'Chọn tài liệu',
    'dashboard.select_document_option': '-- Chọn tài liệu --',
    'dashboard.ai_deep_analysis': 'AI Deep Analysis',
    'dashboard.analyzing': 'Analyzing...',
    'dashboard.analyze': 'Analyze',
    'dashboard.summary': 'Summary',
    'dashboard.key_points': 'Key Points',
    'dashboard.type_label': 'Type:',
    'dashboard.recommendations': 'Recommendations',
    'dashboard.edit_strategy_suggestions': 'Edit Strategy Suggestions',
    'dashboard.loading': 'Loading...',
    'dashboard.get_suggestions': 'Get Suggestions',
    'dashboard.overall_strategy': 'Overall Strategy',
    'dashboard.complexity_label': 'Complexity:',
    'dashboard.suggestions': 'Suggestions',
    'dashboard.issue_label': 'Issue:',
    'dashboard.chat_placeholder': 'Đặt câu hỏi về tài liệu...',
    'dashboard.ai_responding': 'AI đang trả lời...',
    'dashboard.enter_question': 'Nhập câu hỏi...',
    'dashboard.send': 'Gửi',
    'dashboard.key_clauses': 'Key Clauses',
    'dashboard.extracting': 'Extracting...',
    'dashboard.extract': 'Extract',
    'dashboard.extract_hint': 'Nhấn "Extract" để trích xuất điều khoản chính',
    'dashboard.compare_title': 'So sánh tài liệu',
    'dashboard.document_1': 'Tài liệu 1',
    'dashboard.document_2': 'Tài liệu 2',
    'dashboard.select_option': 'Chọn...',
    'dashboard.comparing': 'Đang so sánh...',
    'dashboard.compare': 'So sánh',
    'dashboard.result_label': 'Kết quả:',
    'dashboard.select_doc_to_analyze_title': 'Chọn một tài liệu',
    'dashboard.select_doc_to_analyze_subtitle': 'để phân tích',
    'dashboard.restore': 'Restore',
    'dashboard.delete_permanently': 'Delete permanently',
    'dashboard.chain': 'Chain',
    'dashboard.documents_count': 'documents',
    'dashboard.no_filter_match': 'Không có tài liệu nào khớp với bộ lọc',
    'dashboard.type_pdf': 'PDF',
    'dashboard.type_image': 'Hình ảnh',
    'dashboard.type_doc': 'Tài liệu',
    'stats.total_documents': 'Tổng số tài liệu',
    'stats.verified_by_ai': 'Xác thực bởi AI',
    'stats.storage_used': 'Dung lượng đã dùng',
    'stats.storage_limit': 'Giới hạn:',
    'stats.plan': 'Gói',
    'stats.plan_free': 'Miễn phí',
    'filter.all': 'Tất cả',
    'filter.pdf': 'PDF',
    'filter.image': 'Hình ảnh',
    'filter.verified': 'Đã xác thực',
    'filter.pending': 'Đang chờ',
    'upload.drop_here': 'Kéo và thả tài liệu vào đây',
    'upload.limits': 'PDF, DOC, PNG, JPG — tối đa 50MB mỗi file',
    'upload.choose_folder': 'Chọn thư mục',
    'upload.choose_files': 'Chọn file',
    'upload.folder': 'Thư mục',
    'upload.files_selected': 'Đã chọn {count} file',
    'upload.processing_steps': 'Các bước xử lý',
    'upload.step_upload': 'Tải lên',
    'upload.step_ai_scan': 'AI Quét',
    'upload.step_store_chain': 'Lưu trên Chain',
    'upload.scan_and_upload': 'Quét & Tải lên',
    'upload.n_files': '({count} file)',
    'upload.processing': 'Đang xử lý tài liệu',
    'upload.uploading_files': 'Đang tải lên {count} file...',
    'upload.complete_title': 'Tài liệu đã được xác thực & lưu trữ',
    'upload.complete_desc': 'Đã tải lên thành công {count} file',
    'share.title': 'Chia sẻ',
    'share.wallet_address': 'Địa chỉ ví',
    'share.user_id': 'Mã người dùng',
    'share.receiver_wallet': 'Địa chỉ ví người nhận',
    'share.user_id_label': 'Mã người dùng (6 chữ số)',
    'share.permission': 'Quyền truy cập',
    'share.expires': 'Hết hạn (tùy chọn)',
    'share.password_protect': 'Bảo vệ bằng mật khẩu',
    'share.add_password': 'Thêm mật khẩu bảo vệ',
    'share.enter_password': 'Nhập mật khẩu...',
    'share.sharing': 'Đang chia sẻ...',
    'share.share_button': 'Chia sẻ',
    'share.shared_with': 'Đã chia sẻ với ({count})',
    'share.expires_date': 'Hết hạn:',
    'share.has_password': '🔒 Có mật khẩu',
    'share.error_user_id': 'User ID phải là 6 chữ số',
    'share.error_wallet': 'Vui lòng nhập địa chỉ ví',
    'share.success': 'Đã chia sẻ tài liệu thành công!',
    'share.error': 'Chia sẻ thất bại',
    'share.permission_viewer': 'Viewer - chỉ xem',
    'share.permission_commenter': 'Commenter - xem + AI chat',
    'share.permission_editor': 'Editor - xem + sửa',
    'share.permission_owner': 'Owner - toàn quyền',
    'preview.delete': 'Xóa tài liệu',
    'preview.folder_contents': 'Nội dung thư mục',
    'preview.no_preview': 'Không có bản xem trước cho loại tệp này',
    'preview.file_info': 'Thông tin tệp',
    'preview.type': 'Loại',
    'preview.unknown': 'Không xác định',
    'preview.size': 'Kích thước',
    'preview.created_at': 'Ngày tạo',
    'preview.cid': 'CID',
    'preview.ai_summary': 'AI Tổng quan',
    'preview.ai_verified': 'AI Xác thực',
    'preview.onchain': 'On-Chain',
    'preview.shared_by': 'Chia sẻ bởi',
    'activity.recent': 'Hoạt động gần đây',
    'activity.onchain_events': 'Sự kiện on-chain',
    'activity.just_now': 'vừa xong',
    'activity.m_ago': '{n} phút trước',
    'activity.h_ago': '{n} giờ trước',
    'activity.d_ago': '{n} ngày trước',
    'command.upload': 'Tải tài liệu lên',
    'command.recent': 'Xem gần đây',
    'command.connect_wallet': 'Kết nối ví',
    'command.search': 'Tìm kiếm hành động...',
    'command.no_results': 'Không tìm thấy hành động.',
    'command.actions': 'Hành động',
    'home.hero_badge': 'Bảo mật Blockchain',
    'home.hero_heading': 'Lưu trữ tài liệu phi tập trung an toàn',
    'home.hero_description': 'Bảo vệ quyền sở hữu dữ liệu của bạn với công nghệ Web3.\nMã hóa đầu cuối, xác thực AI và lưu trữ vĩnh viễn trên IPFS.',
    'home.hero_cta': 'Bắt đầu ngay',
    'home.hero_learn_more': 'Tìm hiểu thêm',
    'home.features_section_title': 'Tính năng bảo mật tối ưu',
    'home.features_section_subtitle': 'Giải pháp lưu trữ tài liệu thế hệ mới cho kỷ nguyên số.',
    'home.features_view_all': 'Xem tất cả tính năng',
    'home.feature_security_title': 'Bảo mật tuyệt đối',
    'home.feature_security_desc': 'Dữ liệu được mã hóa quân sự và chia nhỏ trên mạng lưới phi tập trung.',
    'home.feature_ai_title': 'Xác thực AI',
    'home.feature_ai_desc': 'Tự động nhận diện và phân loại tài liệu thông minh bằng trí tuệ nhân tạo.',
    'home.feature_blockchain_title': 'Blockchain native',
    'home.feature_blockchain_desc': 'Lưu vết mọi giao dịch và thay đổi trên sổ cái bất biến của blockchain.',
    'home.feature_easy_title': 'Dễ dàng sử dụng',
    'home.feature_easy_desc': 'Giao diện tối giản, thân thiện giúp bạn quản lý tài liệu chỉ với vài cú click.',
    'home.highlight_title': 'Quyền riêng tư là ưu tiên hàng đầu',
    'home.highlight_description': 'Chúng tôi không bao giờ có thể truy cập tài liệu của bạn. Chỉ có bạn nắm giữ chìa khóa duy nhất cho kho lưu trữ của mình.',
    'home.highlight_cta': 'Khám phá công nghệ mã hóa',
    'home.stats_docs_saved': 'Tài liệu đã lưu',
    'home.stats_uptime': 'Thời gian duy trì',
    'home.stats_leaks': 'Rò rỉ dữ liệu',
    'home.stats_users': 'Người dùng tin dùng',
  },
  en: {
    'nav.dashboard': 'Dashboard',
    'nav.my_documents': 'My Documents',
    'nav.shared': 'Shared',
    'nav.connect': 'Connect Wallet',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    'nav.light_mode': 'Light mode',
    'nav.dark_mode': 'Dark mode',
    'sidebar.dashboard': 'Dashboard',
    'sidebar.my_documents': 'My Documents',
    'sidebar.ai_analysis': 'AI Analysis',
    'sidebar.favorites': 'Favorites',
    'sidebar.recent': 'Recent',
    'sidebar.trash': 'Trash',
    'sidebar.folders': 'Folders',
    'sidebar.new_folder': 'New Folder',
    'sidebar.upload_file': 'Upload File',
    'sidebar.storage': 'Storage',
    'sidebar.profile': 'Profile',
    'sidebar.settings': 'Settings',
    'sidebar.etherscan': 'View on Etherscan',
    'sidebar.logout': 'Logout',
    'profile.back': '← Back',
    'profile.edit': 'Edit Profile',
    'profile.overview': 'Overview',
    'profile.web3': 'Web3 Identity',
    'profile.activity': 'Activity',
    'profile.storage': 'Storage',
    'profile.security': 'Security',
    'profile.edit_tab': 'Edit',
    'profile.upload_avatar': 'Change avatar',
    'profile.storage_used': 'MB used',
    'profile.storage_of': '/',
    'profile.usage_percent': '% used',
    'profile.upgrade_pro': 'Upgrade to Pro',
    'profile.account_info': 'Account Info',
    'profile.user_id': 'User ID',
    'profile.joined': 'Joined',
    'profile.auth_method': 'Auth Method',
    'profile.public_profile': 'Public Profile',
    'profile.yes': 'Yes',
    'profile.no': 'No',
    'profile.ens_name': 'ENS Name',
    'profile.no_ens': 'No ENS name. Register to display a name instead of your wallet address.',
    'profile.register_ens': 'Register ENS',
    'profile.nfts': 'DocVault NFTs',
    'profile.no_nfts': 'No DocNFT yet. Mint NFTs by verifying documents on-chain.',
    'profile.onchain_stats': 'On-chain Stats',
    'profile.docs_onchain': 'Docs on-chain',
    'profile.signings': 'Signings',
    'profile.nfts_minted': 'NFTs minted',
    'profile.activity_history': 'Activity History',
    'profile.loading_activity': 'Loading activity history...',
    'profile.storage_detail': 'Storage Details',
    'profile.used': 'Used',
    'profile.remaining': 'Remaining',
    'profile.total_limit': 'Total Limit',
    'profile.plan_free': 'Free',
    'profile.plan_pro': 'Pro',
    'profile.plan_business': 'Business',
    'profile.plan_enterprise': 'Enterprise',
    'profile.current': 'Current',
    'profile.upgrade': 'Upgrade',
    'profile.security_title': 'Security',
    'profile.wallet_auth': 'Web3 Wallet Auth',
    'profile.wallet_auth_desc': 'Login with MetaMask signature — no password required.',
    'profile.nonce_rotation': 'Nonce Rotation',
    'profile.nonce_rotation_desc': 'New nonce per login — prevents replay attacks.',
    'profile.jwt_expiry': 'Auto JWT Expiry',
    'profile.jwt_expiry_desc': 'Token expires after 7 days, re-sign to renew.',
    'profile.e2e_encryption': 'End-to-End Encryption (IPFS)',
    'profile.e2e_encryption_desc': 'File content is encrypted before uploading to IPFS.',
    'profile.enabled': 'Enabled',
    'profile.active': 'Active',
    'profile.days': 'days',
    'profile.coming_soon': 'Coming Soon',
    'profile.edit_info': 'Basic Information',
    'profile.saved': 'Saved',
    'profile.display_name': 'Display Name',
    'profile.bio': 'Bio',
    'profile.twitter': 'Twitter/X',
    'profile.github': 'GitHub',
    'profile.website': 'Website',
    'profile.public_toggle': 'Public Profile',
    'profile.save_changes': 'Save Changes',
    'profile.documents': 'Documents',
    'profile.verified': 'Verified',
    'profile.on_chain': 'On-Chain',
    'profile.shared': 'Shared',
    'profile.signed': 'Signed',
    'profile.anonymous': 'Anonymous',
    'profile.saving': 'Saving...',
    'profile.logout': 'Logout',
    'profile.price_free': 'Free',
    'profile.price_pro': '$19/month',
    'profile.price_business': '$79/month',
    'profile.price_enterprise': '$299/month',
    'profile.unlimited': 'Unlimited',
    'profile.nfts_count': 'NFTs',
    'profile.placeholder_display_name': 'Enter display name...',
    'profile.placeholder_bio': 'Write a short bio...',
    'profile.placeholder_twitter': 'https://twitter.com/...',
    'profile.placeholder_github': 'https://github.com/...',
    'profile.placeholder_website': 'https://...',
    'home.hero_title': 'Document Management',
    'home.hero_subtitle': 'Secured with Web3 + AI',
    'home.connect_prompt': '🚀 Start with Web3 Wallet',
    'home.terms': 'Terms',
    'home.privacy': 'Privacy Policy',
    'home.contact': 'Contact',
    'home.copyright': '© 2024 DocVault Ecosystem. Secure Optimism.',
    'dashboard.dashboard_title': 'Dashboard',
    'dashboard.dashboard_subtitle': 'Manage documents, AI verification and blockchain storage',
    'dashboard.document_name': 'Document Name',
    'dashboard.type': 'Type',
    'dashboard.status': 'Status',
    'dashboard.date': 'Date',
    'dashboard.actions': 'Actions',
    'dashboard.no_documents': 'No documents yet',
    'dashboard.folder_label': 'folder',
    'dashboard.onchain_badge': 'On-Chain',
    'dashboard.ai_verified_badge': 'AI Verified',
    'dashboard.pending_badge': 'Pending',
    'dashboard.save_proof_onchain': 'Save Proof On-Chain',
    'dashboard.saved_onchain': 'Saved On-Chain',
    'dashboard.share': 'Share',
    'dashboard.ai_summary': 'AI Summary',
    'dashboard.select_doc_prompt_title': 'Select a document from the table',
    'dashboard.select_doc_prompt_subtitle': 'to view details',
    'dashboard.password_required': 'Password Required',
    'dashboard.password_protected_message': 'This document is password protected. Please enter the password to view.',
    'dashboard.enter_password': 'Enter password...',
    'dashboard.password_required_error': 'Password is required',
    'dashboard.wrong_password': 'Wrong password',
    'dashboard.cancel': 'Cancel',
    'dashboard.verifying': 'Verifying...',
    'dashboard.confirm': 'Confirm',
    'dashboard.open_folder': 'Open folder',
    'dashboard.preview': 'Preview',
    'dashboard.star': 'Star',
    'dashboard.unstar': 'Unstar',
    'dashboard.store_on_chain': 'Store On-Chain',
    'dashboard.store_all_on_chain': 'Store all On-Chain',
    'dashboard.delete': 'Delete',
    'dashboard.delete_folder': 'Delete folder',
    'dashboard.docvault': 'DocVault',
    'dashboard.favorites': 'Favorites',
    'dashboard.recent': 'Recent',
    'dashboard.trash': 'Trash',
    'dashboard.deleted_documents': 'Deleted documents',
    'dashboard.favorite_documents': 'Favorite documents',
    'dashboard.recent_documents': 'Recent documents',
    'dashboard.all_documents': 'All documents',
    'dashboard.search': 'Search...',
    'dashboard.upload': 'Upload',
    'dashboard.search_results': 'Search results',
    'dashboard.files_found': 'files',
    'dashboard.no_results_found': 'No results found',
    'dashboard.clear': 'Clear',
    'dashboard.trash_is_empty': 'Trash is empty',
    'dashboard.no_favorite_documents': 'No favorite documents',
    'dashboard.no_documents_yet': 'No documents yet',
    'dashboard.upload_now': 'Upload now',
    'dashboard.unknown_type': 'unknown',
    'dashboard.my_files': 'My Files',
    'dashboard.name': 'Name',
    'dashboard.size': 'Size',
    'dashboard.shared_with_me': 'Shared with me',
    'dashboard.no_shared_documents': 'No documents shared with you yet',
    'dashboard.edit_permission': 'Edit',
    'dashboard.view_permission': 'View',
    'dashboard.from_user': 'from',
    'dashboard.back_to_root': 'Back to root',
    'dashboard.percent_used': '% used',
    'dashboard.switch_language': 'Switch to English',
    'dashboard.light_mode': 'Light mode',
    'dashboard.dark_mode': 'Dark mode',
    'dashboard.anonymous': 'Anonymous',
    'dashboard.ai_analysis_title': 'AI Analysis',
    'dashboard.ai_analysis_subtitle': 'Analyze documents with AI',
    'dashboard.ai_chat_clauses_tab': 'AI Chat & Clauses',
    'dashboard.compare_tab': 'AI Compare',
    'dashboard.select_document_label': 'Select document',
    'dashboard.select_document_option': '-- Select document --',
    'dashboard.ai_deep_analysis': 'AI Deep Analysis',
    'dashboard.analyzing': 'Analyzing...',
    'dashboard.analyze': 'Analyze',
    'dashboard.summary': 'Summary',
    'dashboard.key_points': 'Key Points',
    'dashboard.type_label': 'Type:',
    'dashboard.recommendations': 'Recommendations',
    'dashboard.edit_strategy_suggestions': 'Edit Strategy Suggestions',
    'dashboard.loading': 'Loading...',
    'dashboard.get_suggestions': 'Get Suggestions',
    'dashboard.overall_strategy': 'Overall Strategy',
    'dashboard.complexity_label': 'Complexity:',
    'dashboard.suggestions': 'Suggestions',
    'dashboard.issue_label': 'Issue:',
    'dashboard.chat_placeholder': 'Ask about the document...',
    'dashboard.ai_responding': 'AI is responding...',
    'dashboard.enter_question': 'Enter a question...',
    'dashboard.send': 'Send',
    'dashboard.key_clauses': 'Key Clauses',
    'dashboard.extracting': 'Extracting...',
    'dashboard.extract': 'Extract',
    'dashboard.extract_hint': 'Press "Extract" to extract key clauses',
    'dashboard.compare_title': 'Compare documents',
    'dashboard.document_1': 'Document 1',
    'dashboard.document_2': 'Document 2',
    'dashboard.select_option': 'Select...',
    'dashboard.comparing': 'Comparing...',
    'dashboard.compare': 'Compare',
    'dashboard.result_label': 'Result:',
    'dashboard.select_doc_to_analyze_title': 'Select a document',
    'dashboard.select_doc_to_analyze_subtitle': 'to analyze',
    'dashboard.restore': 'Restore',
    'dashboard.delete_permanently': 'Delete permanently',
    'dashboard.chain': 'Chain',
    'dashboard.documents_count': 'documents',
    'dashboard.no_filter_match': 'No documents match the selected filter',
    'dashboard.type_pdf': 'PDF',
    'dashboard.type_image': 'Image',
    'dashboard.type_doc': 'Document',
    'stats.total_documents': 'Total Documents',
    'stats.verified_by_ai': 'Verified by AI',
    'stats.storage_used': 'Storage Used',
    'stats.storage_limit': 'Limit:',
    'stats.plan': 'Plan',
    'stats.plan_free': 'Free',
    'filter.all': 'All',
    'filter.pdf': 'PDF',
    'filter.image': 'Image',
    'filter.verified': 'Verified',
    'filter.pending': 'Pending',
    'upload.drop_here': 'Drag & drop your documents here',
    'upload.limits': 'PDF, DOC, PNG, JPG — max 50MB per file',
    'upload.choose_folder': 'Choose Folder',
    'upload.choose_files': 'Choose Files',
    'upload.folder': 'Folder',
    'upload.files_selected': '{count} file(s) selected',
    'upload.processing_steps': 'Processing Steps',
    'upload.step_upload': 'Upload',
    'upload.step_ai_scan': 'AI Scan',
    'upload.step_store_chain': 'Store on Chain',
    'upload.scan_and_upload': 'Scan & Upload',
    'upload.n_files': '({count} files)',
    'upload.processing': 'Processing documents',
    'upload.uploading_files': 'Uploading {count} file(s)...',
    'upload.complete_title': 'Documents verified & stored',
    'upload.complete_desc': '{count} file(s) uploaded successfully',
    'share.title': 'Share',
    'share.wallet_address': 'Wallet Address',
    'share.user_id': 'User ID',
    'share.receiver_wallet': 'Recipient wallet address',
    'share.user_id_label': 'User ID (6 digits)',
    'share.permission': 'Permission',
    'share.expires': 'Expires (optional)',
    'share.password_protect': 'Password protect',
    'share.add_password': 'Add password protection',
    'share.enter_password': 'Enter password...',
    'share.sharing': 'Sharing...',
    'share.share_button': 'Share',
    'share.shared_with': 'Shared with ({count})',
    'share.expires_date': 'Expires:',
    'share.has_password': '🔒 Password protected',
    'share.error_user_id': 'User ID must be 6 digits',
    'share.error_wallet': 'Please enter wallet address',
    'share.success': 'Document shared successfully!',
    'share.error': 'Share failed',
    'share.permission_viewer': 'Viewer - view only',
    'share.permission_commenter': 'Commenter - view + AI chat',
    'share.permission_editor': 'Editor - view + edit',
    'share.permission_owner': 'Owner - full access',
    'preview.delete': 'Delete document',
    'preview.folder_contents': 'Folder contents',
    'preview.no_preview': 'No preview available for this file type',
    'preview.file_info': 'File information',
    'preview.type': 'Type',
    'preview.unknown': 'Unknown',
    'preview.size': 'Size',
    'preview.created_at': 'Created',
    'preview.cid': 'CID',
    'preview.ai_summary': 'AI Summary',
    'preview.ai_verified': 'AI Verified',
    'preview.onchain': 'On-Chain',
    'preview.shared_by': 'Shared by',
    'activity.recent': 'Recent Activity',
    'activity.onchain_events': 'On-chain events',
    'activity.just_now': 'just now',
    'activity.m_ago': '{n}m ago',
    'activity.h_ago': '{n}h ago',
    'activity.d_ago': '{n}d ago',
    'command.upload': 'Upload Document',
    'command.recent': 'View Recent',
    'command.connect_wallet': 'Connect Wallet',
    'command.search': 'Search actions...',
    'command.no_results': 'No actions found.',
    'command.actions': 'Actions',
    'home.hero_badge': 'Blockchain Secured',
    'home.hero_heading': 'Secure Decentralized Document Storage',
    'home.hero_description': 'Protect your data ownership with Web3 technology.\nEnd-to-end encryption, AI verification, and permanent storage on IPFS.',
    'home.hero_cta': 'Get Started',
    'home.hero_learn_more': 'Learn More',
    'home.features_section_title': 'Optimal Security Features',
    'home.features_section_subtitle': 'Next-generation document storage for the digital age.',
    'home.features_view_all': 'View all features',
    'home.feature_security_title': 'Absolute Security',
    'home.feature_security_desc': 'Military-grade encryption, distributed across a decentralized network.',
    'home.feature_ai_title': 'AI Verification',
    'home.feature_ai_desc': 'Smart document recognition and classification using AI.',
    'home.feature_blockchain_title': 'Blockchain Native',
    'home.feature_blockchain_desc': 'Every transaction and change recorded on an immutable blockchain ledger.',
    'home.feature_easy_title': 'Easy to Use',
    'home.feature_easy_desc': 'Minimal, friendly interface for managing documents in just a few clicks.',
    'home.highlight_title': 'Privacy is Our Top Priority',
    'home.highlight_description': 'We can never access your documents. Only you hold the unique key to your storage.',
    'home.highlight_cta': 'Explore Encryption Technology',
    'home.stats_docs_saved': 'Documents Saved',
    'home.stats_uptime': 'Uptime',
    'home.stats_leaks': 'Data Leaks',
    'home.stats_users': 'Trusted Users',
  },
}

interface LanguageContextType {
  lang: Lang
  setLang: (lang: Lang) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType>({
  lang: 'vi',
  setLang: () => {},
  t: (key) => key,
})

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    const saved = localStorage.getItem('docvault_lang')
    return (saved === 'vi' || saved === 'en') ? saved : 'vi'
  })

  const setLang = (l: Lang) => {
    setLangState(l)
    localStorage.setItem('docvault_lang', l)
  }

  const t = (key: string): string => translations[lang][key] || key

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)
